### ISSUE TITLE
Setup for dappeteer is broken with latest metamask commit.

### ISSUE THREAD

**Issue by keithfrazier98** [ChainSafe/dappeteer#101]
Simple **_bandaid_** for people who just need to run tests, go into node_modules/@chainsafe/dappeteer/dist/jest/setup.js and just change line 18 to use `v10.8.1` instead of `latest`.

The `latest` version of metamask is hardcoded in[ setup.ts](https://github.com/ChainSafe/dappeteer/blob/master/src/jest/setup.ts) here https://github.com/ChainSafe/dappeteer/blob/0484bc22a32a5693ac2d0fe3d29bfdabc0ccc001/src/jest/setup.ts#L7

The latest version of metamask is a breaking change for dappeteer because of the removal of this id `#ftf-chk1-label` that was used in the setup process. 

Reproduce
Use the launch function:  https://github.com/ChainSafe/dappeteer/blob/0484bc22a32a5693ac2d0fe3d29bfdabc0ccc001/src/index.ts#L56 
to launch a new instance of dappeteer. While trying to sign in it will throw this timeout error: 

![Screen Shot 2022-03-10 at 4 30 21 PM](https://user-images.githubusercontent.com/67716169/157778476-16a3c324-e681-4eb3-8adc-632e915c8793.png)

Commit [7929a92c6696a2b970c4cf1610b1804f7466587c](https://github.com/MetaMask/metamask-extension/blob/7929a92c6696a2b970c4cf1610b1804f7466587c/ui/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js)  was the last commit in metamask where dappeteer was working fine, then this [pull request](https://github.com/MetaMask/metamask-extension/pull/13461) is where the breaking change was merged from commit [429451de236b28cf30b53362a07bad58b7b3a22a](https://github.com/MetaMask/metamask-extension/blob/429451de236b28cf30b53362a07bad58b7b3a22a/ui/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js). 

The  `#ftf-chk1-label` was the ID for the checkbox "Show Secret Recovery Phrase" checkbox, which now is in an [entirely different component from before](https://github.com/MetaMask/metamask-extension/blob/master/ui/components/app/create-new-vault/create-new-vault.js#L181) and has `create-new-vault__show-srp-checkbox` as its new ID:
https://github.com/MetaMask/metamask-extension/blob/c86a64209694ac314d877bcc4f88263a84509b26/ui/components/app/create-new-vault/create-new-vault.js#L181

Node v16.0.0
Mac OS Monterey V12.2.1
Testing framework: Jest
dAppeteer  v^2.4.1
React: ^17.0.2

**Comment by kennetheversole** [comment]
Is there a reason that `  const browser = await dappeteer.launch(puppeteer, { metamaskVersion: 'v10.8.1' }); `  does not work for overriding the metamask version?

**Comment by BeroBurny** [comment]
should be fixed in 3.0.0-rc.0
