### ISSUE TITLE
Added Avax network but getting unavailable on this network error

### ISSUE THREAD

**Issue by mzahirr** [ChainSafe/dappeteer#103]
**Describe the problem**
I have added Avax network but getting unavailable on this network error. Is there any suggestion ? 

`  await metamask.addNetwork({
        networkName: "Avalanche Network",
        rpc: "https://api.avax.network/ext/bc/C/rpc",
        chainId: "43114",
        symbol: "AVAX",
        explorer : "https://snowtrace.io/"}
        )`

![hata](https://user-images.githubusercontent.com/5872984/159186589-38022d2c-0f29-4946-9c11-6c6af84ffe58.png)

**System:**
- OS: Windows
- NodeJs version [e.g v17.2.0]

**Comment by wtesler** [comment]
Chain id should be a number, not a string.

**Comment by wtesler** [comment]
Chain id should be a number, not a string.
