### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by hmouhtar** [ChainSafe/dappeteer#107]
Apparently this isn't working with the latest Metamask release? 

It gets stuck at this point (with the sample code provided): 

<img width="1205" alt="Screenshot 2022-05-02 at 14 29 03" src="https://user-images.githubusercontent.com/15305350/166233799-8157648e-ebf9-4ce0-8354-778e6fa58a7a.png">
 
Error: (node:80045) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `button[data-testid='page-container-footer-next']:not([disabled])` failed: timeout 30000ms exceeded

**Comment by Anastacia-43** [comment]
HI @hmouhtar have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by Ophelia45** [comment]
I will suggest you contact metamask support and click on the live chat message logo to talk with a Developer from metamask through their live chat Developers forum to help you sort this issue out right away. https://metamaskzendesk.helpsconnect.live/#

**Comment by BeroBurny** [comment]
should be fixed in 3.0.0-rc.0
