### ISSUE TITLE
Getting blocked by cloudflare

### ISSUE THREAD

**Issue by GnidaKid69** [ChainSafe/dappeteer#108]
I'm trying to log in to opensea but, i'm getting cloudflare ddos protection and it's stuck in endless redirect loop. In dev console it says enable javascript... I searched for solutions and only one that partially worked was about using puppeteer-extra-stealth-plugin. It was passing that check but in few minutes browser was crashing. But when I tested on my home network, where there was no ddos protection, code ran just fine. So browser crash was cause by puppeteer-extra when combined with dappeteer. Do you have any other solution to pass cloudflare's ddos protection or can you find and fix the issue of browser crashing. Thanks.
Also I tried it on multiple devices and results were the same.

**Comment by tinyc-z** [comment]
await page.setUserAgent('Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0')

**Comment by mpetrunic** [comment]
This issue is not related to dappeteer^^
