### ISSUE TITLE
setting gas and gasLimit for confirmTransaction stops a function.

### ISSUE THREAD

**Issue by masafumimori** [ChainSafe/dappeteer#111]
**Describe the bug**
confirmTransaction method with gas and gasLimit arguments does not finish confirming the transaction and pausing popup open. (like in a photo attached)
I am using the method to make transactions in Arthswap on Astar Network.
Without specifying gas and gasLimit, it confirms the transaction although the transaction never gets fulfilled.

**To Reproduce**
1. set all required info and process (process details can be seen in [here](https://codesandbox.io/s/node-js-forked-r9dn4c?file=/src/index.js)
2. set gas or gasLimit when calling confirmTransaction
3. run node index.js

※Arthswap : https://app.arthswap.org/#/swap

**Expected behavior**
Set gas and gasLimit as being set in confirmTransaction args and complete trnasaction.

**Screenshots**
![Screenshot 2022-06-06 at 16 05 34](https://user-images.githubusercontent.com/71799690/172113265-447ace60-1a47-4bdc-b84f-32436c5bd878.png)

**System:**
- OS:macOS Monterey
- OS version 12.0
- NodeJs version v16.13.0
- dAppeteer version 2.4.1

**Comment by BeroBurny** [comment]
Implemented in 3.0.0-rc.0
