### ISSUE TITLE
How avoid import seed to metamask every time

### ISSUE THREAD

**Issue by xflag** [ChainSafe/dappeteer#120]
When I bootstrap dappeteer,it need import seed,add network,switch network,it seems too slow.Futhermore,it failed sometimes when add new network to metamask.Are there any way to launch by my own prepared metamask to avoid these duplicate steps?

**Comment by ccforeverd** [comment]
```ts
  const browser = await dappeteer.launch(puppeteer, {
    // metamaskVersion: 'v10.15.0',
    metamaskPath: join(__dirname, '../metamask/v10_15_0'),
    // args: ['--lang=en-US,en', '--proxy-server=127.0.0.1:7890'],
    args: ['--lang=en-US,en'],
    devtools: true
  })
```

**Comment by mpetrunic** [comment]
We could try adding an option to cache browser data after metamask is set-up. This needs more research.

**Comment by mpetrunic** [comment]
@BeroBurny @danforbes This would be useful to speed up snap testing and to insure a clean state for every test but it's out of scope for M1

**Comment by mpetrunic** [comment]
There are multiple options how to achieve this:
- start using persisted context (we already do that for playwright)
- use rdp API to import context (how metamask does it)
