### ISSUE TITLE
Installation of other extensions 

### ISSUE THREAD

**Issue by chrschae** [ChainSafe/dappeteer#126]
Hello, i would like to use this package with preinstalled metamask and other extensions. (using userDataDir arg from pupeteer, so extensions would be saved there)
I noticed that i cannot install any extension on the browser via UI (i use chrome, install via chrome web store or crx). 
The Error i get when trying to install is "Installation is disabled". 
![image](https://user-images.githubusercontent.com/11799176/185748739-15a7ea8c-69c7-441a-9fe2-80ff1f751024.png)

these are my launch parameters
`{
        metamaskVersion: 'v10.15.0',
        userDataDir: './browser_data2',
        headless: false,
        product: "chrome",
        args: [
            '--ignore-certificate-errors',
            '--lang=en-US,en;q=0.9',
        ],
        executablePath : "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
        defaultViewport: null,
        slowMo: 25,
        ignoreDefaultArgs: [
            "--disable-extensions",
            "--enable-automation"
        ],
}`
I was able to load saved extensions like this with pupeteer (without this package)
How can i load my extension without reinstalling it every launch? 

Thanks in advance

**Comment by mpetrunic** [comment]
Not 100% that dappeteer would work if you have other extensions. Why would you need other extensions?

**Comment by BeroBurny** [comment]
there is no point in using another extension because implementation details will require redo everything to make it work
