### ISSUE TITLE
pleases help me sir？ 

### ISSUE THREAD

**Issue by nanfan66** [ChainSafe/dappeteer#129]
code：
  const browser = await dappeteer.launch(puppeteer, { metamaskVersion: 'v10.15.0' , headless: false});
  const metamask = await dappeteer.setupMetamask(browser,'v10.15.0');
problem：
TimeoutError: waiting for selector `.//button[contains(text(), 'Get Started')]` failed: timeout 30000ms exceeded

**Comment by BeroBurny** [comment]
Please fulfill the issue with an issue form => https://github.com/ChainSafe/dappeteer/issues/new/choose
