### ISSUE TITLE
Add instructions to integrate with jest-puppeteer

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/dappeteer#13]

**Comment by mpetrunic** [comment]
Needs changes in code. Basically we need to just download metamask and return metamask path + [args](https://github.com/NodeFactoryIo/dappeteer/blob/master/src/index.ts#L41). cc @BeroBurny

**Comment by MikeyZat** [comment]
This feature would be amazing.

When I was doing the integration myself, I needed to do custom `setup.js` and `teardown.js` to re-place the global jest-puppeteer browser with dappeteer browser.

**Comment by mpetrunic** [comment]
> This feature would be amazing.
> 
> When I was doing the integration myself, I needed to do custom `setup.js` and `teardown.js` to re-place the global jest-puppeteer browser with dappeteer browser and figuring it out took ages.

@MikeyZat Does this work for you: https://github.com/ChainSafe/dappeteer/pull/40 ?

**Comment by MikeyZat** [comment]
@mpetrunic looks good from the code perspective, can't wait for it being merged 🚀
