### ISSUE TITLE
confirmTransaction() is not working

### ISSUE THREAD

**Issue by cody-xld** [ChainSafe/dappeteer#130]
**Describe the bug**
The confirm button is not clicked after creating the transaction 

https://user-images.githubusercontent.com/93906995/188994341-aa6b2617-0aa2-4a33-b30b-0a4a06febb61.mov

**Comment by cody-xld** [comment]
I have tried to use confirmTransaction() in my test class and it turned out to work properly.

Last time, it did not work when I implement it in the util like this
`  
public async confirmTransaction(): Promise<void> {
    if (this.metamaskWallet && this.page) {
      await this.metamaskWallet.page.waitForTimeout(1000);
      await this.metamaskWallet.confirmTransaction();
    }
  }
`

**Comment by mpetrunic** [comment]
Are you trying with the latest version? Could be slow loading of Metamask, maybe we need to increase wait timeout

**Comment by cody-xld** [comment]
I used [Release v3.0.0-rc.0](https://github.com/ChainSafe/dappeteer/releases/tag/v3.0.0-rc.0) when I encountered this issue. What I did was increased the wait time to 1500ms after clicking the pay button in my dApp.

I believe the issue is because my dApp need some time to transfer the data.

**Comment by Tbaut** [comment]
The line is fine between adding some blanket `wait` in the lib and having them slow down tests uselessly for all user. Since there is no way to wait exactly the right amount of time, I believe such issues will appear regularly unfortunately, and the solution is for users to add some wait.
