### ISSUE TITLE
I have tried to use confirmTransaction() in my test class and it turned out to work properly.

### ISSUE THREAD

**Issue by MyTrueWallet** [ChainSafe/dappeteer#133]
I have tried to use confirmTransaction() in my test class and it turned out to work properly.

Last time, it did not work when I implement it in the util like this
```  
public async confirmTransaction(): Promise<void> {
    if (this.metamaskWallet && this.page) {
      await this.metamaskWallet.page.waitForTimeout(1000);
      await this.metamaskWallet.confirmTransaction();
    }
  }
```

_Originally posted by @cody-xld in https://github.com/ChainSafe/dappeteer/issues/130#issuecomment-1240254600_

**Comment by mpetrunic** [comment]
Not sure what issue is here
