### ISSUE TITLE
@cody-xld

### ISSUE THREAD

**Issue by MyTrueWallet** [ChainSafe/dappeteer#134]
**Describe the bug**

**To Reproduce**

**Logs**
```shell
Some Logs from console
```

**Expected behavior**

**Screenshots**

**System:**
- OS version [e.g. 22]
- NodeJs version [e.g v15.8.0]
- dAppeteer version [e.g. 2.2.0]
- testing framework [e.g jest]
- testing framework version [e.g 26.0]

**Additional context**

**Comment by BeroBurny** [comment]
empty issue
