### ISSUE TITLE
Unable to setupMetamask on 3.0.0

### ISSUE THREAD

**Issue by panella87** [ChainSafe/dappeteer#155]
I'm not being able to setup metamask, after .setupMetamask has been called chromium stay stuck to metamask welcome page and then the script fails for timeout
```
var browser = await dappeteer.launch(puppeteer, {
    metamaskVersion: "v10.15.0",
    headless: false,
    defaultViewport: false,
    args: ["--start-maximized"],
})
var metamask = await dappeteer.setupMetamask(browser, { seed: metamaskSeedKey, password: metamaskPassword });
```

- OS: Windows 11 21H2
- dAppeteer 3.0.0 - 3.0.0-rc.0
- puppeteer 14.0.0 - 18.2.1
- Metamask 10.15.0

Downgrading to older version i have no problem setting un metamask with the same piece of code:
- dAppeteer 2.4.1
- puppeteer 13.3.2
- Metamask 10.8.1

**Comment by dynamitesushi** [comment]
If you're using 3.0.0, try using `dappeteer.bootsrap` as per the documentation. 

```
const [metamask, page, browser] = await dappeteer.bootstrap(puppeteer, { seed: metamaskSeedKey, password: metamaskPassword, metamaskVersion: 'v10.15.0' });
```

**Comment by panella87** [comment]
Thanks for your reply, i tried also boostraping using the method you suggested without luck

> If you're using 3.0.0, try using `dappeteer.bootsrap` as per the documentation.
> 
> ```js
> const [metamask, page, browser] = await dappeteer.bootstrap(puppeteer, { seed: metamaskSeedKey, password: metamaskPassword, metamaskVersion: 'v10.15.0' });
> ```


I will give it a try when i get back home and post the results

> 
> Your app might also be stuck on a page where you have to confirm trust to use MetaMask on the website, I've not figured out how to bypass this but you can run the following snippet in your code to get around this issue:
> 
> ```js
> const pages = await browser.pages();
> await pages[1].reload();
> await pages[1].waitForNavigation();
> 
> // click continue
> await pages[1].evaluate(() => document.querySelector('.btn-primary').click());
> 
> // click connect
> await pages[1].evaluate(() => document.querySelector('.btn-primary').click());
> ```

**Comment by hongda3141** [comment]
when using that code I was get stuck at the "welcome" page, and failed to click the "start metamask" button automatic.
here is my code of index.js:
```javascript
import puppeteer from 'puppeteer';
import dappeteer from '@chainsafe/dappeteer';

async function main() {
  const [metamask, page, browser] = await dappeteer.bootstrap(puppeteer, { seed: "my seed", password: "my password", metamaskVersion: 'v10.15.0' });
  const pages = await browser.pages();
  await pages[1].reload();
  await pages[1].waitForNavigation();

  // click continue
  await pages[1].evaluate(() => document.querySelector('.btn-primary').click());

  // click connect
  await pages[1].evaluate(() => document.querySelector('.btn-primary').click());
  // you can change the network if you want
  await metamask.switchNetwork('ropsten');

  // you can import a token
  await metamask.addToken({
    tokenAddress: '0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa',
    symbol: 'KAKI',
  });

  // go to a dapp and do something that prompts MetaMask to confirm a transaction
  await page.goto('http://my-dapp.com');
  const payButton = await page.$('#pay-with-eth');
  await payButton.click();

  // 🏌
  await metamask.confirmTransaction();
}

main();
```
and my package.json :
```json5
{
  "name": "test_dappeteer",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "type": "module",
  "devDependencies": {
    "@chainsafe/dappeteer": "^3.0.0",
    "puppeteer": "^18.2.1"
  },
  "scripts": {
    "test": "node index.js"
  }
}

```

**Comment by dynamitesushi** [comment]
> ```js
>   await page.goto('http://my-dapp.com');
> ```

Don't think I get this screen, do you have a screenshot?

**Comment by dynamitesushi** [comment]
> when using that code I was get stuck at the "welcome" page, and failed to click the "start metamask" button automatic. here is my code of index.js:
> 
> ```js
> import puppeteer from 'puppeteer';
> import dappeteer from '@chainsafe/dappeteer';
> 
> async function main() {
>   const [metamask, page, browser] = await dappeteer.bootstrap(puppeteer, { seed: "my seed", password: "my password", metamaskVersion: 'v10.15.0' });
>   const pages = await browser.pages();
>   await pages[1].reload();
>   await pages[1].waitForNavigation();
> 
>   // click continue
>   await pages[1].evaluate(() => document.querySelector('.btn-primary').click());
> 
>   // click connect
>   await pages[1].evaluate(() => document.querySelector('.btn-primary').click());
>   // you can change the network if you want
>   await metamask.switchNetwork('ropsten');
> 
>   // you can import a token
>   await metamask.addToken({
>     tokenAddress: '0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa',
>     symbol: 'KAKI',
>   });
> 
>   // go to a dapp and do something that prompts MetaMask to confirm a transaction
>   await page.goto('http://my-dapp.com');
>   const payButton = await page.$('#pay-with-eth');
>   await payButton.click();
> 
>   // 🏌
>   await metamask.confirmTransaction();
> }
> 
> main();
> ```
> 
> and my package.json :
> 
> ```js
> {
>   "name": "test_dappeteer",
>   "version": "1.0.0",
>   "main": "index.js",
>   "license": "MIT",
>   "type": "module",
>   "devDependencies": {
>     "@chainsafe/dappeteer": "^3.0.0",
>     "puppeteer": "^18.2.1"
>   },
>   "scripts": {
>     "test": "node index.js"
>   }
> }
> ```

Don't think I get this screen, do you have a screenshot?

**Comment by hongda3141** [comment]
@dynamitesushi  like this, which i can not click the "get started" button and stuck there.
![Screenshot_2022-11-11_05-20-05](https://user-images.githubusercontent.com/25719952/201339721-c39f39f9-01eb-489f-82fd-e6a8b179c306.png)

**Comment by mpetrunic** [comment]
> when using that code I was get stuck at the "welcome" page, and failed to click the "start metamask" button automatic. here is my code of index.js:
> 
> ```js
> import puppeteer from 'puppeteer';
> import dappeteer from '@chainsafe/dappeteer';
> 
> async function main() {
>   const [metamask, page, browser] = await dappeteer.bootstrap(puppeteer, { seed: "my seed", password: "my password", metamaskVersion: 'v10.15.0' });
>   const pages = await browser.pages();
>   await pages[1].reload();
>   await pages[1].waitForNavigation();
> 
>   // click continue
>   await pages[1].evaluate(() => document.querySelector('.btn-primary').click());
> 
>   // click connect
>   await pages[1].evaluate(() => document.querySelector('.btn-primary').click());
>   // you can change the network if you want
>   await metamask.switchNetwork('ropsten');
> 
>   // you can import a token
>   await metamask.addToken({
>     tokenAddress: '0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa',
>     symbol: 'KAKI',
>   });
> 
>   // go to a dapp and do something that prompts MetaMask to confirm a transaction
>   await page.goto('http://my-dapp.com');
>   const payButton = await page.$('#pay-with-eth');
>   await payButton.click();
> 
>   // 🏌
>   await metamask.confirmTransaction();
> }
> 
> main();
> ```
> 
> and my package.json :
> 
> ```js
> {
>   "name": "test_dappeteer",
>   "version": "1.0.0",
>   "main": "index.js",
>   "license": "MIT",
>   "type": "module",
>   "devDependencies": {
>     "@chainsafe/dappeteer": "^3.0.0",
>     "puppeteer": "^18.2.1"
>   },
>   "scripts": {
>     "test": "node index.js"
>   }
> }
> ```

Tried this code locally and your seed was invalid but I went passed Getting started.
I also tried the example in the original issue description and it worked. 
I will close this issue, and reopen it if somebody can post a GitHub repo that will demonstrate the issue.
