### ISSUE TITLE
Unable to sign typed data when the message area has a scroll bar

### ISSUE THREAD

**Issue by j05u3** [ChainSafe/dappeteer#156]
**Describe the bug**
In my tests I was unable to sign typed data when the message area has a scroll bar

**To Reproduce**
Inside dappeteer do the following:
1. Go to [OpenSea](https://opensea.io/)
3. Connect wallet
4. Try to lower the price of an already listed NFT that you own
5. Use `metamask.sign()` to approve the signature.

**Expected behavior**
To sign the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/7897132/195957988-6d9cfab9-1512-4593-96de-b07634506f4f.png)

**System:**
- OS: Windows
- OS version: 10
- NodeJs version: 16.13.2
- dAppeteer version: 3.0.0
- testing framework: mocha
- testing framework version: 9.1.3

It looks like we need to click the little arrow down button on the right bottom part of the message area.

**Comment by BeroBurny** [comment]
Resolved with #191
