### ISSUE TITLE
Add parameters 'per_page' or 'page' in the API of get metamask-extension

### ISSUE THREAD

**Issue by hongda3141** [ChainSafe/dappeteer#165]
**Describe the bug**
When using the Github Releases API of get metamask-extension to list the version we want to download,  if not add parameters 'per_page' and 'page', there will be occur an error like `Version v10.8.1 not found!`, 
could you add parameters 'per_page' of  variable `metamaskReleasesUrl` in https://github.com/ChainSafe/dappeteer/blob/master/src/setup/metamaskDownloader.ts#L75 like `https://api.github.com/repos/metamask/metamask-extension/releases?per_page=100` or something else

**To Reproduce**
running app within code `const browser = await launch(puppeteer, DAPPETEER_DEFAULT_CONFIG);`

**Logs**
```shell
Error: Jest: Got error running globalSetup - /home/runner/work/axon/axon/tests/e2e/jest/setup.js, reason: "Version v10.8.1 not found!"
```

**Expected behavior**
success to get metamask-extension version of 10.8.1 that dappeteer need

**System:**
- OS: irrelevant
- dappeteer version 2.4.0

**Comment by mpetrunic** [comment]
@hongda3141 We don't really support old versions of metamask so it makes no sense to fetch more than just the latest few versions. Any reason why you are using the old version instead of recommended one?

**Comment by hongda3141** [comment]
> @hongda3141 We don't really support old versions of metamask so it makes no sense to fetch more than just the latest few versions. Any reason why you are using the old version instead of recommended one?

I`m using v3.0.0 a few days ago, but there was a trouble make process failed, see here for details #155 .
so i have to downgrade the version . I would prefer to use the new version if it could have a detailed guide about how to use it successfully.

**Comment by mpetrunic** [comment]
Closing this as it's not something we wanna support. Will look into #155 ^^
