### ISSUE TITLE
Replace addNetwork/addToken/switchNetwork methods

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/dappeteer#181]
**Is your feature request related to a problem? Please describe.**

Those methods are relicts of history where dapps couldn't send rpc method calls to force metamask to do this. Flow is now different and we should adapt dappeteer to have methods to accept/reject prompts for adding network, token or switching network.

**Describe the solution you'd like**

Replace methods (breaking change), add buttons into our test dapp to add network, switch network and add token.

**Describe alternatives you've considered**

**Additional context**

**Comment by Tbaut** [comment]
This has been fixed in https://github.com/ChainSafe/dappeteer/pull/189 but I'll keep it open to update the documentation.

**Comment by Tbaut** [comment]
There's actually much more than this. Making a dedicated issue.
