### ISSUE TITLE
Built in xvfb support

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/dappeteer#197]
**Is your feature request related to a problem? Please describe.**
Currently, in github actions, we need to run tests with `xvfb-run --auto-servernum  yarn test`
which is unusual to inexperienced devs.

**Describe the solution you'd like**
I would propose that we add additional option `gui: boolean` which would be true by default and utilize https://www.npmjs.com/package/@cypress/xvfb or https://www.npmjs.com/package/xvfb to achieve this in code

**Describe alternatives you've considered**

**Additional context**

cc @BeroBurny

**Comment by Lykhoyda** [comment]
@mpetrunic probably it's not relevant anymore as we are running headless mode in chrome directly

**Comment by mpetrunic** [comment]
Yup
