### ISSUE TITLE
Update docs and readme for `unstable` branch

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/dappeteer#201]
It's currently outdated, what stands out from the top of my head is 
- add/reject token and network https://github.com/ChainSafe/dappeteer/issues/181
- sign typed data #191 
- new `bootstrap` params and return object https://github.com/ChainSafe/dappeteer/pull/167

**Comment by mpetrunic** [comment]
Another thing we should add is:
- example how to write a test for snap (initSnapEnv, testDappPage)

**Comment by Tbaut** [comment]
done in #202
