### ISSUE TITLE
Flaky test results with accept and reject dialog (flask 10.22.2)

### ISSUE THREAD

**Issue by irubido** [ChainSafe/dappeteer#207]
**Tests are failing and passing randomly when accepting/rejecting .invokeSnap is called for snap_confirm rpc method
While writing test-snap integration tests I realized that tests can't find button, depenedent on how button loads.
Hacky fix, i added waitForTimeout(1000) to ensure button loads and can be confirmed with accept/reject
**

**To Reproduce**
1. Go to https://github.com/ChainSafe/test-snaps/pull/2
2. Set flask version in node modules @chainsafe/dappeteer/dist/index.js `exports.RECOMMENDED_METAMASK_VERSION = "v10.22.2";`
3. Try running tests mulitiple times with and without timeout localy

**Logs**
```
confirm snap › snap invoke confirm accept

    TimeoutError: page.waitForSelector: Timeout 100ms exceeded.
    =========================== logs ===========================
    waiting for locator('xpath=//button[contains(text(), \'Approve\')]') to be visible
    ============================================================page.waitForSelector: Timeout 100ms exceeded.
    =========================== logs ===========================
    waiting for locator('xpath=//button[contains(text(), \'Approve\')]') to be visible
    ============================================================

      37 |       ['Test-prompt', 'Test-description', 'Test-textAreaContent'],
      38 |     );
    > 39 |     await dappeteer.snaps.acceptDialog();
         |     ^
      40 |     const result = await resultPromise;
      41 |
      42 |     expect(result).toBe(true);
```

**Expected behavior**
Accept and reject should work

**Screenshots**

![Screenshot 2022-12-06 at 13 39 58](https://user-images.githubusercontent.com/51483483/205915291-b4ac6e5a-1cda-41d5-ae15-5cdf4d1e68e8.png)

**System:**
- OS: macOS Monterey
- OS version 12.3.1
- NodeJs version 16.18.1
- dAppeteer version ^4.0.0-rc.1 forced to use 10.22.2 in node modules
- testing framework jest 
- testing framework version 26.4.2

**Additional context**

**Comment by Lykhoyda** [comment]
@irubido we could close this bug as we increased the timeout for the method to 1000ms
```js
await clickOnButton(page, "Approve", { timeout: 1000 });
```
https://github.com/ChainSafe/dappeteer/commit/cb6abfc4bf751addd2e3f1746db3c4183f495c10
