### ISSUE TITLE
Viewport height and width setup, tests failing remotly

### ISSUE THREAD

**Issue by irubido** [ChainSafe/dappeteer#208]
****
Locally initSnapEnv installs snap properly, remotly on github actions it fails.
It's impossible to scroll to see button in viewport even locally, but button can still be found ("Approve & install") and test work locally.

`dappeteer.page.setViewport({height: 1500, width: 600})` in beforeAll()
sets viewport to late

**To Reproduce**
https://github.com/ChainSafe/test-snaps/pull/2

node_modules/@chainsafe/dappeteer/dist/snap/install.js
```
    if (opts.hasPermissions) {
        await page.waitForSelector('button');
//ADD THIS TIMEOUT, LINE BELOW
        await new Promise((res) => setTimeout(res, 20000));
        await (0, helpers_1.clickOnButton)(page, "Approve & install");
```
stretch screen manually to se "Approve & install" button, scroll doesn't work

Github action logs https://github.com/ChainSafe/test-snaps/pull/2
**Logs**
```
➤ YN0000: [@metamask/test-snap-confirm]:     TimeoutError: page.waitForSelector: Timeout 20000ms exceeded.
➤ YN0000: [@metamask/test-snap-confirm]:     =========================== logs ===========================
➤ YN0000: [@metamask/test-snap-confirm]:     waiting for locator('xpath=//button[contains(text(), \'Approve & install\')]') to be visible
➤ YN0000: [@metamask/test-snap-confirm]:     ============================================================page.waitForSelector: Timeout 20000ms exceeded.
➤ YN0000: [@metamask/test-snap-confirm]:     =========================== logs ===========================
➤ YN0000: [@metamask/test-snap-confirm]:     waiting for locator('xpath=//button[contains(text(), \'Approve & install\')]') to be visible
➤ YN0000: [@metamask/test-snap-confirm]:     ============================================================
➤ YN0000: [@metamask/test-snap-confirm]: 
➤ YN0000: [@metamask/test-snap-confirm]:       15 |
➤ YN0000: [@metamask/test-snap-confirm]:       16 |   beforeAll(async function () {
➤ YN0000: [@metamask/test-snap-confirm]:     > [17](https://github.com/ChainSafe/test-snaps/actions/runs/3621333956/jobs/6104663928#step:5:18) |     ({ dappeteer, snapId, browser } = await initSnapEnv({ 
```

**Expected behavior**
initSnapEnv could have viewport in opts: DappeteerLaunchOptions to force height, maybe then tests wouldn't fail remotly

**Screenshots**
default
![Screenshot 2022-12-06 at 14 02 03](https://user-images.githubusercontent.com/51483483/205919938-d8dfc7ce-8382-4efc-9ba6-4ba80d7d5149.png)

stretched manually
![Screenshot 2022-12-06 at 14 02 07](https://user-images.githubusercontent.com/51483483/205919971-88962cfd-d70e-4488-a6d9-625f5ac934ab.png)

**System:**
- OS version [e.g. 22]
- NodeJs version [e.g v15.8.0]
- dAppeteer version [e.g. 2.2.0]
- testing framework [e.g jest]
- testing framework version [e.g 26.0]

**Additional context**

**Comment by Lykhoyda** [comment]
@irubido we probably could close this issue as we increased the viewport size during the installation step. https://github.com/ChainSafe/dappeteer/commit/cb6abfc4bf751addd2e3f1746db3c4183f495c10
