### ISSUE TITLE
metamaskDownloader runs every single instantiation; api.github.com quota hit

### ISSUE THREAD

**Issue by mike503** [ChainSafe/dappeteer#27]
Doing iterative development, running it inside of a container, etc... every single instantiation of dappeteer hits api.github.com. there does not seem to be a way to force a specific version or zipfile and SKIP all the metamaskDownloader stuff. I didn't realize how bad this was until my IP is blocked for a while due to hitting api.github so much.

**Comment by mpetrunic** [comment]
You can pass version here: https://github.com/NodeFactoryIo/dappeteer/blob/master/src/index.ts#L50 as second argument (Launch options: https://github.com/NodeFactoryIo/dappeteer/blob/master/src/index.ts#L10) so it will stop asking github api for latest metamask version. If we already have downloaded version it won't download again.

**Comment by mpetrunic** [comment]
@mike503 did you manage to resolve this?

**Comment by mpetrunic** [comment]
Closing as there is no response and probably fixed with #33
