### ISSUE TITLE
About the problem that setupmetamask getmetamask and other methods cannot be used

### ISSUE THREAD

**Issue by Lzggno1** [ChainSafe/dappeteer#275]
![image](https://user-images.githubusercontent.com/44811382/217735141-0085ca0c-c0a9-458c-8f3b-c980c712f255.png)
All the methods about enabling metamask will make the program congested. This problem bothers me. Can someone help me?
I tried to print metamsak, but he didn't have anything. The program was blocked。
![image](https://user-images.githubusercontent.com/44811382/217735490-81e8fe99-2e2a-4ad9-81a7-f2c553c21cb3.png)

**Comment by buley** [comment]
This is how headless browsers works. Try passing a `{headless: false}` argument to `bootstrap()` if you want to see the browser instance.

**Comment by BeroBurny** [comment]
Internals of dappeteer's `bootstrap` runs `setupMetaMask` so there is no need to do it again.
Probably the issue is sending empty `seed` and `password` to a method

<hr />

cc @irubido @Lykhoyda seems we need put guards for empty values.

**Comment by Lzggno1** [comment]
i

> dappeteer`bootstrap`运行的内部结构，`setupMetaMask`因此无需再次运行。 可能问题是发送空的`seed`和`password`一个方法
> 
> 抄送@irubido @Lykhoyda似乎我们需要为空值设置警卫。

I have input seed and password, but the three objects returned by bootstrap are undefined

**Comment by BeroBurny** [comment]
Unfortunalty, by provided data im not able to pinpoint a problem.
Try to do follow [example from a readme](https://github.com/ChainSafe/dappeteer#usage).
If that dose not solve it open new issue with fulfilled form.
