### ISSUE TITLE
can't run dappeteer using ubuntu 22

### ISSUE THREAD

**Issue by yaelahda** [ChainSafe/dappeteer#284]
running another puppeteer script is working but dappeteer:
Error: Failed to launch both playwright and puppeteer

**System:**
- OS: Ubuntu
- OS version 22
- NodeJs version 18.14.0
- dappeteer version 3.0.0

**Comment by BeroBurny** [comment]
Thanks for reaching out but we do not support outdated versions.

Try to use the latest (v5), with the latest version of the puppeteer or playwright, if is issue still present please open a bug report.
