### ISSUE TITLE
How to add user agent?

### ISSUE THREAD

**Issue by yaelahda** [ChainSafe/dappeteer#289]
can i custom user agent? 

**System:**
- OS: Windows
- OS version 11
- NodeJs version 18
- dappeteer version 5.0.0

**Comment by BeroBurny** [comment]
It is out of the scope of a project.

There is a puppeteer example of how can be achieved 
You get after getting a new page
> _example_
```js
const { metaMask, browser } = await dappeteer.bootstrap();
const dappPage = await browser.newPage();
```

you can access the underlying `page` object with `getSource`
> _example_
```js
const srcPage = dappPage.getSource();
await srcPage.setuseragent("My secret Agent")
```
- https://pptr.dev/api/puppeteer.page.setuseragent/
