### ISSUE TITLE
There's no 'Cancel' button more in signTypedData

### ISSUE THREAD

**Issue by DANDROZAVR** [ChainSafe/dappeteer#295]
**Describe the bug**
When signing TypedData message, there's no 'Cancel' button more, only 'Reject'. Moreover, there's no any data-test-id assigned to it. 

**To Reproduce**
1. Go to any site, f.e. crew3
2. Click on 'Connect'
3. Approve connecting
4. Try signing (verify part)

![image](https://user-images.githubusercontent.com/48687268/224318733-9c264126-bb6c-4cb3-ace8-49d492d41920.png)
![image](https://user-images.githubusercontent.com/48687268/224318795-d15f647a-8e16-426f-aec3-bf32423b712e.png)

In a code, this error is throwing:
`TimeoutError: Waiting for selector `[data-testid="signature-cancel-button"]` failed: Waiting failed: 30000ms exceeded`

Going from `clickOnLittleDownArrowIfNeeded` function

I believe changing `await page.waitForSelector('[data-testid="signature-cancel-button"]', {
    visible: true,
  });` to `getElementByContent('Reject')` will fix it

**Comment by Arun9650** [comment]
hi l like to work on this issue

**Comment by BeroBurny** [comment]
Thanks for reaching out @DANDROZAVR, can you please provide a bit more information? 
Like dappeter version and a small code snippet?

<hr />
@Arun9650 feel free to dig in, but the issue has too many unknowns to be worked on

**Comment by DANDROZAVR** [comment]
> Thanks for reaching out @DANDROZAVR, can you please provide a bit more information? Like dappeter version and a small code snippet?
> 
> @Arun9650 feel free to dig in, but the issue has too many unknowns to be worked on

Of course. I'm using dappeteer 5.0.1. It's not only  a problem with that function, but almost with every function where "datatest-id" is using (f.e confirmTransaction (edit button), signTypedData and even approve). Metamask is throwing away datatest-id and they are not exist in some tags anymore.

Here's example(don't worry about seed, there's nothing on it):
```
const dappeteer = require("@chainsafe/dappeteer");
const main = async () => {
    const {metaMask, browser, metaMaskPage} = await dappeteer.bootstrap({
        seed: "flight badge audit grass cool print report diesel verb announce girl vocal",
        password: "my-strong-password",
        browser: "chrome",
        headless: false,
    });
    const pagetemp = await browser.newPage()
    await pagetemp.goto('https://galxe.com/superprotocol')
    await metaMask.approve()
    await metaMask.signTypedData()
    await sleep(10000000)
    await setupCrew3(browser, metaMask)
}
main()
```

**Comment by DANDROZAVR** [comment]
Thank you a lot @BeroBurny for fixing it in the newest commit!
