### ISSUE TITLE
How to lunch dappeteer with puppeteer options 

### ISSUE THREAD

**Issue by f-delpoggio** [ChainSafe/dappeteer#296]
**Describe the problem**
I am trying to use the puppeteer options like I use in dappeteer v3.0.0 but in the newer version I don't understand how to use with this options   

![image](https://user-images.githubusercontent.com/87336125/225325869-b5699094-8f91-4e30-ab2f-7eec1be82088.png)

**System:**
- OS: MacOS
- OS version 13.2.1
- NodeJs version v18.13.0
- dappeteer version v5.0.1
- puppeteer version v19.3.0

**Comment by DANDROZAVR** [comment]
You should use "puppeteerOptions". Like this:
![image](https://user-images.githubusercontent.com/48687268/226130317-91d61e85-bbbc-420b-89a9-36db58d22861.png)
