### ISSUE TITLE
Puppeteer always launch on background

### ISSUE THREAD

**Issue by imacrosid** [ChainSafe/dappeteer#310]
**Describe the problem**
I don't understand why puppeteer always running on background?

**System:**
- OS: Windows
- OS version : 10 Home
- NodeJs version : v16.15.1
- dappeteer version: v5.0.1
- puppeteer version: v19.9.1

![image](https://user-images.githubusercontent.com/24670377/233082368-f77d12f8-dd57-4c55-82bb-000280f67730.png)

**Comment by BeroBurny** [comment]
Hey, can you please provide the setup config?

**Comment by imacrosid** [comment]
> Hey, can you please provide the setup config?

![image](https://user-images.githubusercontent.com/24670377/233095147-73c80b8f-2ec9-48b9-a5ca-1d2ee8a05ec8.png)

**Comment by BeroBurny** [comment]
you should keep the heddles option in the root of the setup object
like in the case of following [usage setup from readme ](https://github.com/ChainSafe/dappeteer#usage)
you can run like this
```js
const { metaMask, browser } = await dappeteer.bootstrap({ headless: false });
```

btw it is better to use quoting code that screenshot
reference -> https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by imacrosid** [comment]
It's done, thanks for help.
