### ISSUE TITLE
Crashing when Rate Limited

### ISSUE THREAD

**Issue by Lawlzer** [ChainSafe/dappeteer#32]
If you're rate limited by the API, it crashes when trying to parse JSON, instead of logging an error or throwing or handling it better.

If you go to line 61 (https://github.com/ChainSafe/dappeteer/blob/master/src/metamaskDownloader.ts#L61), and add a log, like:
```
console.log(body); 
for (const result of JSON.parse(body)) {
    console.log('This console.log is not seen ');
```
You get the output:
```
{"message":"API rate limit exceeded for <IP address>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

C:\Users\Kevin\Desktop\DappateerProject\node_modules\@chainsafe\dappeteer\dist\metamaskDownloader.js:87
            for (const result of JSON.parse(body)) {
                                      ^

TypeError: JSON.parse is not a function or its return value is not iterable```

**Comment by mpetrunic** [comment]
Hey @Lawlzer we will look into it, we are doing very little api requests so you shouldn't be rate limited. Are you by any chance running dappeteer in ci?

**Comment by Lawlzer** [comment]
> Hey @Lawlzer we will look into it, we are doing very little api requests so you shouldn't be rate limited. Are you by any chance running dappeteer in ci?

I'm actually remaking browsers (dappeteer.launch, and dappeteer.setupBrowser) quite often, and when setting up the browser, it calls getMetamaskReleases every time. I did a (fairly lazy, but working :P) fix and just made a global variable, after getMetamaskReleases is called once, it sets the global variable to the body, then for every future run it just loads the body. That way I only call the API once, every time I run the file. 

Also, uncommonly (maaaybe one in every 10 times?) when I do this, sometimes I get a crash on the .waitForSelector (timeout) here. https://prnt.sc/1qp52xr
Any idea what might be causing this, off the top of your head?

**Comment by BeroBurny** [comment]
Good catch, the solution is on PR but if you want to reduce the rate limit you should provide a version.

> Also, uncommonly (maaaybe one in every 10 times?) when I do this, sometimes I get a crash on the .waitForSelector (timeout) here. https://prnt.sc/1qp52xr
> Any idea what might be causing this, off the top of your head?

it is kinda messy with focusing windows, if you do something in the exact wrong moment and lose focus or type something that can fail tests, happens a lot to me when I'm trying to multitask :sweat_smile:
