### ISSUE TITLE
API methods addNetwork() in combination with switchNetwork() seems not to work

### ISSUE THREAD

**Issue by OliPelz** [ChainSafe/dappeteer#34]
Hi,

When I ran the following code, I can add a new network but cannot switch to it. Visually I see that the switchNetwork method call does not actually switch anything. Using some from the predefined list such as `ropsten` works perfectly fine.

Any help appreciated.

Thanks,
Oliver

P.S.: using latest dappeteer 2.0.4 downloaded  today.

```javascript
const puppeteer = require('puppeteer');
const dappeteer = require('@chainsafe/dappeteer');

async function main() {
  const browser = await dappeteer.launch(puppeteer);
  const metamask = await dappeteer.setupMetamask(browser);

  await metamask.addNetwork({
    networkName: 'BSC',
    rpc: 'https://bsc-dataseed1.binance.org/',
    chainId: 56,
    symbol: 'BNB',
    explorer: 'https://bscscan.com/',
  });

  await metamask.switchNetwork('BSC');
```

Btw, I can see the newly created network and can manually switch to it.

**Comment by BeroBurny** [comment]
Thanks for reaching out

Can try to add some small delay?
```js
await new Promise(resolve => setTimeout(resolve, 1000));
```
If this does not resolve a problem I will check in detail tomorrow morning.

**Comment by OliPelz** [comment]
Hey @BeroBurny,

Thank you very much for your fast response.

Worked like a charm, adding a bit of a delay before switchNetwork() resolved my problem.

Thanks again,
Oliver

**Comment by mpetrunic** [comment]
@BeroBurny should we add that delay in our code to avoid future similar issues?

**Comment by BeroBurny** [comment]
> @BeroBurny should we add that delay in our code to avoid future similar issues?

PR or ready :eyes:
It is actual problem, in the real case, if someone adds a network like second later metamask will switch to that network
