### ISSUE TITLE
Error while downloading metamask

### ISSUE THREAD

**Issue by MikeyZat** [ChainSafe/dappeteer#37]
I'm using `dappeteer` with `jest-puppeeteer` for automation testing. Coming across this issue when launching the browser.
log:
```
            for (const result of data) {
                                 ^

TypeError: data is not iterable
    at IncomingMessage.<anonymous> (/node_modules/@chainsafe/dappeteer/dist/metamaskDownloader.js:94:34)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
 ```  
  
 It doesn't occur everytime, sometimes it works

**Comment by BeroBurny** [comment]
Hey @MikeyZat  thanks for reaching out.

Which version of dappeteer are you using?

**Comment by MikeyZat** [comment]
@BeroBurny 
```
"@chainsafe/dappeteer": "^2.1.0",
```

**Comment by MikeyZat** [comment]
I assume it might have been caused by the metamask API not responding correctly (you're fetching the metamask versions for downloading purpose).
For a quick fix I'd suggest parsing the response more safely and rejecting with more descriptive error. If you're open for PRs & would accept such a temporary solution, I can make one.

**Comment by BeroBurny** [comment]
> I asyosume it might have been caused by the metamask API not responding correctly (u're fetching the metamask versions for downloading purpose).
> For a quick fix I'd suggest parsing the response more safely and rejecting with more descriptive error. If you're open for PRs & would accept such a temporary solution, I can make one.

fell free to open any PR 😄
