### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir '/var/task/bot/node_modules/@chainsafe/dappeteer/metamask/download

### ISSUE THREAD

**Issue by advissor** [ChainSafe/dappeteer#41]
Hi, 
Is it possible to somehow change the extraction directory where the download is done?

`ERRROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, mkdir '/var/task/bot/node_modules/@chainsafe/dappeteer/metamask/download'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, mkdir '/var/task/bot/node_modules/@chainsafe/dappeteer/metamask/download'","code":"ENOENT","errno":-2,"`

The fs we have is RO, where the node_modules are placed as it is already a bundled application 
So, I think the file doesn't exist, because the download failed (and..there is no error saying about it)

Thanks

**Comment by BeroBurny** [comment]
Hello @advissor 

> Is it possible to somehow change the extraction directory where the download is done?

Currently, it is not possible but we are looking into implementing it in the future.

**Comment by advissor** [comment]
@BeroBurny 

Can we hardcode it or something? 
Maybe just change the loading URL to local node modules folder instead of downloading it every time

**Comment by BeroBurny** [comment]
@advissor there is a new release [v2.2.0](https://github.com/ChainSafe/dappeteer/releases/tag/v2.2.0) with a custom path feature
https://github.com/ChainSafe/dappeteer/blob/master/docs/API.md#launch

**Comment by advissor** [comment]
@BeroBurny Thanks!!!
