### ISSUE TITLE
Turning dappeteer into a puppeteer-extra plugin to enable stealth mode to avoid being blocked by Cloudflare

### ISSUE THREAD

**Issue by rayGoMoon** [ChainSafe/dappeteer#57]
**Problem:** Sometimes dappeteer is detected and blocked by Cloudflare. 

**Solution:** Turning dappeteer into a [puppeteer-extra](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra) plugin enables it to work with [puppeteer-extra-plugin-stealth](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth), thus effectively solving this problem.

**Question:** 

@BeroBurny 

Hi, Bero. Thanks again for your time. 

I just want to know if there is an easy and quick way to implement this feature? And do you have the time to implement it?

Thanks.

**Comment by 3lang3** [comment]
any progress?
Or accept puppeteer instance parameters as before v3?

**Comment by BeroBurny** [comment]
stale, there is issue #313 for future conversations
