### ISSUE TITLE
cannot confirm transaction

### ISSUE THREAD

**Issue by jimmymaise** [ChainSafe/dappeteer#67]
the function confirmTransaction() does not work. It tried to click the confirm button but it does work. The transaction is still not confirmed and the confirm button still displays like not clicked.
Perhaps we need to wait some time before clicking confirm button as it worked when adding code to sleep 5 second and click again

**Comment by matteocasonato** [comment]
same problem here, confirmation appears but button doesn't get pressed

**Comment by BeroBurny** [comment]
should be fixed in 3.0.0-rc.0
