### ISSUE TITLE
"What's new popup" doesn't get closed

### ISSUE THREAD

**Issue by Elyx0** [ChainSafe/dappeteer#68]
![e0d7fe80f0079be19db2483ec69c3370](https://user-images.githubusercontent.com/706218/143147761-050cedb9-ac0b-4adf-b3be-52cfec85aa2f.png)

I see https://github.com/dasanra/dappeteer/commit/3656360e4f891a3e7d1e80e77a40b2cfb83af2c8 added something similar

**Comment by mpetrunic** [comment]
If I remember correctly, everything works even though that popup is shown?

**Comment by Elyx0** [comment]
Could have been the browser size if it doesn't have enough height it might not be able to click it, will recheck.
