### ISSUE TITLE
Dappeteer options not being passed by jest.config.js or package.json (when using the preset)

### ISSUE THREAD

**Issue by budowski** [ChainSafe/dappeteer#75]
**Describe the bug**
Dappeteer options not being passed by jest.config.js or package.json (when using `@chainsafe/dappeteer` Jest preset).

**To Reproduce**
package.json -> `jest` key:
```
"jest": {
    "preset": "@chainsafe/dappeteer",
    "dappeteer": {
        "metamaskVersion": "v10.1.1"
    }
}
```

Same thing happens when using `jest.config.js` file.
Other Jest options (e.g. verbose=false) do work when using the same config.

**Expected behavior**
Dappeteer options should be passed as-is when using the preset.
Currently the workaround is to use custom setup/teardown/environment files that pass these options.

**System:**
- OS: MacOS
- OS version v12.1
- NodeJs version: v14.18.2
- dAppeteer version v2.3.0
- testing framework: jest
- testing framework version: v27.4.5

**Comment by sofianeOuafir** [comment]
Creating a dappeteer.config.js file worked for me:

```

// in dappeteer.config.js

const config = {
  dappeteer: {
    headless: process.env.IN_BROWSER === 'false',
    metamaskVersion: 'v10.25.0',
  },
  metamask: {
    seed:
      'seed here',
    password: 'password here',
  },
}

module.exports = config


```

**Comment by BeroBurny** [comment]
seems as resolved
