### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by marcelooblan2016** [ChainSafe/dappeteer#77]
**Describe the problem**
Hi may i ask, if the chromium/metamask extension that we used here is not compromised? I lost my funds on my own trading bot  wallet, I may be wrong.

Here is the address that did the transaction: https://polygonscan.com/address/0xe2d55868a3eb68da4403e8506e23d015149f0b94

Best regards,
**System:**
- OS version [e.g. 22]
- NodeJs version [e.g v15.8.0]
- dAppeteer version [e.g. 2.2.0]
- testing framework [e.g jest]
- testing framework version [e.g 26.0]

**Comment by mpetrunic** [comment]
This library is downloading metamask from official github: https://github.com/ChainSafe/dappeteer/blob/master/src/metamaskDownloader.ts#L75

It's more likely that you committed your keys somewhere.

**Comment by marcelooblan2016** [comment]
> This library is downloading metamask from official github: https://github.com/ChainSafe/dappeteer/blob/master/src/metamaskDownloader.ts#L75
> 
> It's more likely that you committed your keys somewhere.

Oh my, so stupid of me. it make sense now. Thank you for the clarification.
