### ISSUE TITLE
Import PK test dose not test if is key imported correctly

### ISSUE THREAD

**Issue by BeroBurny** [ChainSafe/dappeteer#96]
Based on PR #95

Test of `importPk` should check if a key is imported currently

**Comment by Tbaut** [comment]
This is fixed by now in `unstable` right? 
https://github.com/ChainSafe/dappeteer/blob/unstable/test/basic.spec.ts#L148

Or do you mean we should verify that the added account has an expected address?

**Comment by BeroBurny** [comment]
seems right
