### ISSUE TITLE
Using `connect` instead of `launch` to attach dAppeteer to an existing browser instance

### ISSUE THREAD

**Issue by vphilot** [ChainSafe/dappeteer#99]
**Describe the problem**
I would like to have dAppeteer launch inside an existing headed Chrome (spin up by Jest) for integration testing. 

Currently, the `launch` method won't support that as it will launch a new browser. Is there any way we can make the `connect` method work with the library? E.g

```js
    const browser = await puppeteer.connect({
      browserURL: `http://localhost:${debuggingPort}`,
    })

    const metamask = await dappeteer.setupMetamask(browser)
```

(Testing the code snippet above  doesn't yield any results). Thank you

**System:**
- OS: MacOs
- OS version: 12.2.1
- NodeJs version: 6.13.0
- dAppeteer version: 2.2.0
- testing framework: Cypress
- testing framework version: 9.3.1

**Comment by BeroBurny** [comment]
Hey.

You can try to get WebSocket URL by open url `http://localhost:${debuggingPort}/json/version` on-field webSocketDebbugerUrl and use puppeteer connect with `browserWSEndpoint`

```ts
const browser = await puppeteer.connect({
  browserWSEndpoint: browserWSEndpoint from url,
});

const metamask = await dappeteer.setupMetamask(browser);
```

**Comment by vphilot** [comment]
@BeroBurny that seems to work. Thank you for your help!

**Comment by blank1u** [comment]
cool
